CREATE TABLE ServiceInstance (
   SERVICE_INSTANCE_ID   VARCHAR(32) NOT NULL,

   SERVICE_ID   VARCHAR(32) NOT NULL,
   PLAN_ID   VARCHAR(32) NOT NULL,
   ORGANIZATION_GUID   VARCHAR(32) NOT NULL,
   SPACE_GUID   VARCHAR(32) NOT NULL,
   DASHBOARD_URL   VARCHAR(128) NOT NULL,

   PRIMARY KEY (SERVICE_INSTANCE_ID)
);

CREATE TABLE ServiceInstanceBinding (
   SERVICE_INSTANCE_BINDING_ID   VARCHAR(32) NOT NULL,

   SERVICE_INSTANCE_ID   VARCHAR(32) NOT NULL,
   CREDENTIALS   VARCHAR(128) NOT NULL,
   SYSLOG_DRAIN_URL   VARCHAR(128) NOT NULL,
   APP_GUID   VARCHAR(32) NOT NULL,

   PRIMARY KEY (SERVICE_INSTANCE_BINDING_ID),

   FOREIGN KEY(SERVICE_INSTANCE_ID) REFERENCES ServiceInstance(SERVICE_INSTANCE_ID)
);
